# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        entry: ruff check run.py voicevox_engine test --select E4,E7,E9
        language: system
        types: [file, python]
        stages: [push]
        pass_filenames: false
